---
- hosts: all
  become: yes
  roles:
    - docker

- hosts: postgres
  become: yes
  roles:
    - postgres

- hosts: memcached
  become: yes
  roles:
    - memcached

- hosts: redis
  become: yes
  roles:
    - redis

- hosts: rabbitmq
  become: yes
  roles:
    - rabbitmq

- hosts: zulip
  become: yes
  roles:
    - zulip
