---
- hosts: all
  become: yes
  roles:
    - docker

- hosts: zulip
  become: yes
  tasks:
    - name: Init a new swarm
      docker_swarm:
        state: present
        advertise_addr: 192.168.77.25 # this will obviously be dynamic
      register: swarm_info
    - name: Create an Overlay network
      docker_network:
        name: zulip_network
        driver: overlay
        scope: swarm
        attachable: yes
        ipam_config:
          - subnet: 10.10.10.0/24

- hosts:
    - redis
    - rabbitmq
    - memcached
    - postgres
  become: yes
  tasks:
    - name: Join swarm as workers
      docker_swarm:
        state: join
        advertise_addr: hostvars[groups['ansible_hostname'][0]]
        join_token: "{{ hostvars[groups['zulip'][0]].swarm_info.swarm_facts.JoinTokens.Worker }}"
        remote_addrs: [ '192.168.77.25:2377' ] # should be dynamic

- hosts: all
  become: yes
  tasks:
    - name: Create base directory
      file:
        path: /opt/docker/zulip/
        state: directory
    - name: Create postgres directory
      file:
        path: /opt/docker/zulip/postgresql/data
        state: directory
    - name: Create rabbit directory
      file:
        path: /opt/docker/zulip/rabbitmq
        state: directory
    - name: Create redis directory
      file:
        path: /opt/docker/zulip/redis
        state: directory
    - name: Create zulip directory
      file:
        path: /opt/docker/zulip/zulip
        state: directory

- hosts: zulip
  become: yes
  roles:
    - docker-swarm
