---
- name: Install nfs-common
  apt:
    name: nfs-common
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Create base directory
  file:
    path: /opt/docker/zulip/
    state: directory

- name: Create postgres directory
  file:
    path: /opt/docker/zulip/postgresql/data
    state: directory

- name: Create rabbit directory
  file:
    path: /opt/docker/zulip/rabbitmq
    state: directory

- name: Create redis directory
  file:
    path: /opt/docker/zulip/redis
    state: directory

- name: Create zulip directory
  file:
    path: /opt/docker/zulip/zulip
    state: directory

- name: Mount filestore
  mount:
    path: /opt/docker/zulip/
    src: "{{ filestore_ip }}:/{{ filestore_name }}"
    fstype: nfs
    opts: defaults
    state: mounted     