- name: create a filestore instance
  gcp_filestore_instance:
    name: teste
    zone: "{{ gcp_zone }}"
    tier: STANDARD
    file_shares:
    - capacity_gb: 1024
      name: share1
    networks:
    - network: "{{ network.name }}"
      modes:
      - MODE_IPV4
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: filestore