- name: Download and extract Elasticsearch
  unarchive:
    src: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.0-linux-x86_64.tar.gz
    dest: /usr/local/bin
    remote_src: yes


- name: Configure Elasticsearch
  template:
    src: "elasticsearch.yml.j2"
    dest: /usr/local/bin/elasticsearch-7.5.0/config/elasticsearch.yml
    owner: root
    #group: elasticsearch
    mode: 0777

# - name: Start Elasticsearch
#   shell: /usr/local/bin/elasticsearch-7.5.0/bin/elasticsearch &



- name: Download and extract Kibana
  unarchive:
    src: https://artifacts.elastic.co/downloads/kibana/kibana-7.5.0-linux-x86_64.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Configure Kibana
  template:
    src: "kibana.yml.j2"
    dest: /usr/local/bin/kibana-7.5.0-linux-x86_64/config/elasticsearch.yml
    owner: root
    mode: 0777

# - name: Start Kibana
#   shell: /usr/local/bin/kibana-7.5.0/bin/kibana &