
---

#####################################################################
###                          REPOSITORY                           ###
#####################################################################

- name: HTTPS APT transport for Elasticsearch repository.
  apt:
    name: apt-transport-https
    state: present

- name: Add Elasticsearch apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    state: present
    update_cache: true


    
#####################################################################
###                       ELASTIC SEARCH                          ###
#####################################################################  

- name: Install Elasticsearch.
  package:
    name: elasticsearch
    state: "{{ elasticsearch_package_state }}"


- name: Configure Elasticsearch.
  #become: yes 
#   replace:
#     path: /etc/elasticsearch/elasticsearch.yml
#     regexp: item.var
#     replace: item.replace
#     owner: root
#     group: root
#     mode: 0644
#   loop:
#     - {var: '^#network.host:.*', replace: 'network.host: 0.0.0.0'}
#     - {var: '^#discovery.seed_hosts:.*', replace: 'discovery.seed_hosts: []'}
#     - {var: '^#cluster.initial_master_nodes:.*', replace: 'cluster.initial_master_nodes: [{{ monitor_vm_ip }}]'}
  template:
    src: "elastic.yml.j2"
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660


- name: Configs
  become: yes
  shell: sysctl -w vm.max_map_count=262144


- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: "{{ elasticsearch_service_state }}"
    enabled: "{{ elasticsearch_service_enabled }}"



#####################################################################
###                           KIBANA                              ###
#####################################################################

- name: Install Kibana.
  package:
    name: "{{ kibana_package }}"
    state: "{{ kibana_package_state }}"


- name: Copy Kibana configuration.
#   replace:
#     path: /etc/kibana/kibana.yml
#     regexp: item.var
#     replace: item.replace
#   loop:
#     - {var: '#server.host:.*', replace: 'server.host: {{monitor_vm_ip}}'}
#     - {var: '#elasticsearch.hosts:.*', replace: 'elasticsearch.hosts: ["http://{{monitor_vm_ip}}:9200"]'}
  template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
#     owner: root
#     group: root
#     mode: 0644


- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"