---

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python3-pip
docker_compose_stable_release_url: https://github.com/docker/compose/releases/download/1.25.0/docker-compose-Linux-x86_64
docker_compose_location: /usr/local/bin/docker-compose
