
---

#####################################################################
###                          REPOSITORY                           ###
#####################################################################

# - name: HTTPS APT transport for metricbeat repository.
#   apt:
#     name: apt-transport-https
#     state: present

- name: Add metricbeat apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add metricbeat repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main'
    state: present
    update_cache: true


    
#####################################################################
###                          METRICBEAT                           ###
#####################################################################  

- name: Install Metricbeat.
  package:
    name: metricbeat
    state: "{{ metricbeat_package_state }}"


- name: Configure metricbeat.
  template:
    src: "{{item}}.j2"
    dest: /etc/metricbeat/{{item}}
  loop:
    - "metricbeat.yml"
    - "metricbeat.reference.yml"
#     owner: root
#     group: root
#     mode: 0644

- name: Enable modules
  become: yes
  shell: metricbeat modules enable memcached nginx postgresql rabbitmq redis system 

- name: Setup metricbeat
  become: yes
  shell: metricbeat setup --dashboards

- name: Start metricbeat
  service:
    name: metricbeat
    state: "{{ metricbeat_service_state }}"
    enabled: "{{ metricbeat_service_enabled }}"
