---

# Cria VMs, discos, redes, firewalls......
- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: gcp
      vars:
        gcp_zone: europe-west4-a
        gcp_region: europe-west4
        gcp_project: vernal-branch-257511
        gcp_cred_kind: serviceaccount
        gcp_cred_file: ~/.gcloud/gcloud.json
        gcp_machine_type: n1-standard-1
        source_image: projects/ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20191113
        disk_size: 10
        disks:
          - disk-01
          - disk-02
        disks_db:
          - disk-db-01
          - disk-db-02
        addresses:
          - addr-01
          - addr-02
        addresses_db:
          - addr-db-01
          - addr-db-02
        instances:
          - { index: 1, tag: app, name: zulip}         
          - { index: 2, tag: lb, name: nginx}
        instances_db:
          - { index: 1, tag: database, name: db-master}
          - { index: 2, tag: database-slave, name: db-slave}


# # Para cada tipo de máquinas (tag)
# - hosts: all
#   become: yes
#   roles:
#     - { role: users, payload: users.yml }

# - hosts: database
#   become: yes
#   roles:
#     - { role: db-postgresql, addresses: '*', version: '9.5' }
#     - { role: postgresql-db, dbname: 'passwords_production' }
#     - {
#       role: postgresql-user,
#       username: 'deployer',
#       password: "{{ lookup('passwordstore','ansible/uc/db create=true length=8') }}",
#       dbname: 'passwords_production'
#       }

# - hosts: app
#   become: yes
#   roles:
#     - { role: app-passwords, payload: app-passwords.yml }

# - hosts: lb
#   become: yes
#   roles:
#     - web-nginx
#     - {
#       role: nginx-vhost,
#       template: uwsgi-vhost,
#       fqdn: uc.lsd.di.uminho.pt,
#       root: /srv/apps,
#       backend_addresses: "{{ groups['app'] }}",
#       backend_port: 5000
#       }
