---

# Cria VMs, discos, redes, firewalls......
- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: gcp
      vars:
        gcp_zone: europe-west3-a
        gcp_region: europe-west3
        gcp_project: vernal-branch-257511
        gcp_cred_kind: serviceaccount
        gcp_cred_file: ~/.gcloud/gcloud.json
        gcp_machine_type: n1-standard-1
        source_image: projects/ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20191113
        disk_size: 10
        disks:
          - disk-pm-01
          - disk-pm-02
        addresses:
          - addr-pm-01
          - addr-pm-02
        instances:
          - { index: 1, tag: app, name: zulip}         
          - { index: 2, tag: monitor, name: monitor}




# - hosts: all
#   become: yes
#   roles:
#     - { role: users, payload: users.yml }

# - hosts: database
#   become: yes
#   roles:
#     - { role: db-postgresql, addresses: '*', version: '9.6' }
#     - { role: postgresql-db, dbname: 'zulip' }
#     - { role: postgresql-user, username: 'deployer', password: '123456', dbname: 'zulip' }


- hosts: monitor
  become: yes
  roles:
    - { role: elastic-kibana, monitor_vm_ip: "{{ hostvars[groups['monitor'][0]].ansible_all_ipv4_addresses[0] }}" } # {{ groups['monitor'][0] }}


- hosts: app # mudar para all
  become: yes
  roles:
    - { role: metricbeat, monitor_vm_ip: "{{ hostvars[groups['monitor'][0]].ansible_all_ipv4_addresses[0] }}" }


# - hosts: app
#   become: yes
#   roles:
#     - { role: app-passwords, payload: app-passwords.yml }

# - hosts: lb
#   become: yes
#   roles:
#     - web-nginx
#     - {
#       role: nginx-vhost,
#       template: uwsgi-vhost,
#       fqdn: uc.lsd.di.uminho.pt,
#       root: /srv/apps,
#       backend_addresses: "{{ groups['app'] }}",
#       backend_port: 5000
#       }
