- name: create a network
  gcp_compute_network:
    name: zulip-network
    auto_create_subnetworks: 'false'
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: network

- name: create a subnetwork
  gcp_compute_subnetwork:
    name: zulip-test-network-subnet
    region: "{{ gcp_region }}"
    network: "{{ network }}"
    ip_cidr_range: 192.168.0.0/16
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: subnetwork  

- name: create a address
  gcp_compute_address:
    name: "{{ item }}"
    region: "{{ gcp_region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
    subnetwork: "{{ subnetwork }}"
  register: address
  loop: "{{ addresses }}"

- name: internal/external firewall rules
  gcp_compute_firewall:
    name: "internal-external-rules"
    allowed:
      - ip_protocol: tcp
        ports:
          - '22'
          - '80'
          - '443'
          - '5601'
          - '9200'
      - ip_protocol: icmp
    network:
      selfLink: "global/networks/{{ network.name }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present


# Necessário abrir portas para Monitoring
- name: internal firewall rules
  gcp_compute_firewall:
    name: "internal-rules"
    allowed:
      - ip_protocol: tcp
        ports:
          - "0-65535"
      - ip_protocol: udp
        ports:
          - "0-65535"
      - ip_protocol: icmp
    source_ranges: # IP DA NOVA NETWORK? 10.240.0.0/16?
      - 0.0.0.0/0 #10.128.0.0/9
    network:
      selfLink: "global/networks/{{ network.name }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
