---
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ packages }}"

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 0EBFCD88

- name: Add Docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Download current stable release of Docker Compose
  get_url:
    url: "{{ docker_compose_stable_release_url }}"
    dest: "{{ docker_compose_location }}"

- name: Apply executable permissions to Docker Compose
  file:
    path: "{{ docker_compose_location }}"
    mode: u+x

- name: Update apt to install Docker CE
  apt:
    update_cache: yes
    name: docker-ce
    state: latest

- name: Install Docker and Docker compose modules for Python
  pip:
    name:
      - docker
      - docker-compose
